### PR TITLE
Incorrect require statement in container configs

### PR DESCRIPTION
**Pull request by weierophinney**
I believe that config.php require statements in container template configuration files, for example [config/container-pimple-interop.php](https://github.com/zendframework/zend-expressive-skeleton/blob/master/src/Composer/Resources/config/container-pimple-interop.php), should be coded this way: `require 'config/config.php';`, rather than `require 'config.php';`, because of the `chdir(dirname(__DIR__));` in [index.php](https://github.com/zendframework/zend-expressive-skeleton/blob/master/public/index.php). I've just stumbled upon a strange issue of config.php not being loaded on a Windows machine.

### CODE REVIEW

**Comment by weierophinney** [comment]
I've converted this issue into a pull request, implementing the suggested approach. @xtreamwayz — please review!

**Comment by xtreamwayz** [comment]
@weierophinney Tested on Windows 10 and it's working. But I don't use xampp, I've got my own server stack.

@nikolaposa Can you confirm this solution works with xampp?

**Comment by xtreamwayz** [comment]
@weierophinney One thing though, I think this file can be deleted: ``src/Composer/Resources/config/container-pimple.php``.

I used it a while ago for experimenting with Pimple 3.x.

**Comment by nikolaposa** [comment]
@xtreamwayz I've just checked it with XAMPP, it works. :+1:

**Pull request merged**
