### PR TITLE
don't let composer timeout after 300 seconds

### PR DESCRIPTION
**Pull request by basz**
24 hrs seems enough of a working day

### CODE REVIEW

**Comment by weierophinney** [comment]
@basz This one is interesting, because what actually happens is that the `php -S` invocation *continues running in the background* even when composer times out!

I almost think it may be more worth simply noting exactly that. Thoughts?

**Comment by basz** [comment]
sure... not here (OSX). port isn't in use

```
COMPOSER_PROCESS_TIMEOUT=1 composer serve
// times out
COMPOSER_PROCESS_TIMEOUT=1 composer serve
// times out

ps -ax | grep php
noth'
```

**Comment by weierophinney** [comment]
@basz Interesting; must be different behavior between environments (I'm on linux).

I'll go ahead and merge, and make a note about the timeout.

**Comment by xtreamwayz** [comment]
I have tested this on windows and I get a timeout as well after 300 seconds.

**Pull request merged**
