### PR TITLE
Added a cleanup routing to the installer

### PR DESCRIPTION
**Pull request by weierophinney**
A new Composer `post-install-cmd`/`post-update-cmd` now recursively removes the `src/Composer/` directory, ensuring a clean skeleton on completion of the install/update.

### CODE REVIEW

**Comment by weierophinney** [comment]
@xtreamwayz I figured out how to do a cleanup. :smile:

**Comment by ezimuel** [comment]
@weierophinney just tried with composer install and update, the `src/Composer` folder is removed.

**Comment by xtreamwayz** [comment]
@weierophinney Nice.

1 thing though:

```php
"scripts": {
    "post-install-cmd": [
        "App\\Composer\\OptionalPackages::install",
        "App\\Composer\\OptionalPackages::cleanUp"
    ],
    "post-update-cmd": [
        "App\\Composer\\OptionalPackages::install",
        "App\\Composer\\OptionalPackages::cleanUp"
    ]
},
```

Looks better.

**Comment by weierophinney** [comment]
@xtreamwayz True, but we have 4 separate commands we're using, not two:

- `pre-install-cmd`
- `post-install-cmd`
- `pre-update-cmd`
- `post-update-cmd`

So we can't use the array notation here.

**Comment by weierophinney** [comment]
@xtreamwayz Also, the reason for doing the `post-*-cmd` vs having those as part of the installer is to ensure order of operations. If I did them within the `pre-*-cmd` operations, I was getting failures in composer preventing install.

**Comment by weierophinney** [comment]
@xtreamwayz As it turns out, I was wrong; we *can* do this as part of the install/update command. I left the routine intact as a separate method, but now call that from within the install command. Works flawlessly. :smile:

**Pull request merged**
