### PR TITLE
Run travis build on PHP 7.2 and removed HHVM build

### PR DESCRIPTION
**Pull request by webimpress**
- [x] removed hhvm from travis build
- [x] added PHP 7.2 build to travis configuration
- [x] removed IRC and Slack notifications
- [x] updated travis configuration to with legacy dependencies (PHPUnit 5 on PHP5.6)
- [x] set column=120 for composer show output
- [x] added `twig/twig` to legacy dependencies in travis config (v2 supports only PHP7+, v1 - PHP5.6+)

### CODE REVIEW

**Comment by webimpress** [comment]
Nightly build is failing because of Aura.Di on PHP 7.2.
There is already fix in the library: https://github.com/auraphp/Aura.Di/commit/79d337cab869dd076f3a2630d395bbd78e561cd1
but it is still not yet released.

**Comment by froschdesign** [comment]
@webimpress 
I see the same problem again and again: inconsistence in Travis scripts. 
Can you compare this Travis script with [zend-session](https://github.com/zendframework/zend-session/blob/master/.travis.yml)? @weierophinney includes some more changes there. Thanks!

_We need a boilerplate for the Travis configuration file!_

**Comment by webimpress** [comment]
@froschdesign PR is updated now

**Comment by xtreamwayz** [comment]
superseded by #179

**Pull request closed without merging**
