### PR TITLE
set config_cache_path config to data/cache/config-cache.php

### PR DESCRIPTION
**Pull request by samsonasik**
with inside `data/cache` directory

### CODE REVIEW

**Comment by weierophinney** [comment]
What's the motivation for this? What purpose will this change serve?

I ask, because if we move it, then folks who are familiar with the _current_ location will no longer be looking for it in the correct location, and may think config caching is not occurring, or that it is, but the location of the caching is a mystery (is it in memory? in a database? what happened to the file?!?!? etc.).

From a technical point of view, it's not an issue, particularly as zf-development-mode uses the config key to find the location when it clears the cache file. I'm mainly concerned about the _human_ point of view here, and want to understand (a) motivation behind the change, and (b) how we communicate that to existing users already familiar with how config caching works.

**Comment by samsonasik** [comment]
We already have `data/cache` directory, as it is a cached file, I think it is better to use `data/cache` directory instead of parent `data` directory itself. I think expressive skeleton only installed once, for legacy expressive application, user is still using parent `data` directory.

**Comment by weierophinney** [comment]
> We already have data/cache directory, as it is a cached file, I think it is better to use data/cache directory instead of parent data directory itself.

That said, the `data/cache/` directory could be used by those using the filesystem adapter of zend-cache, which results in configuration caching (an application-wide concern) being mixed in with fragment caching, which could lead to collisions (though unlikely).

My point is **why** is it better to push it under that directory, particularly considering the concerns I raised?

**Comment by samsonasik** [comment]
if we check ZendSkeletonApplication, the cache path for config cache and module config cache located to `data/cache`, I think it is better to save in there as well, while it is still ok, just about consistency

**Comment by weierophinney** [comment]
I've looked through the various scripts:

- `bin/clear-config-cache.php` (mapped to `composer clear-config-cache`) uses the `$config['config_cache_path']` value to determine where the file exists.
- zf-development-mode also uses the config value.

Knowing this, I think we can safely accept this for version 3.

**Comment by weierophinney** [comment]
Thanks, @samsonasik!

**Pull request closed without merging**
