### PR TITLE
Changing Pimple DI container

### PR DESCRIPTION
**Pull request by Sam-Burns**

### CODE REVIEW

**Comment by Sam-Burns** [comment]
Ref https://github.com/zendframework/zend-expressive/pull/228 , https://github.com/zendframework/zend-expressive/issues/129 ; \cc @weierophinney

**Comment by xtreamwayz** [comment]
I didn't test this code but I'm pretty sure it doesn't work. You can't just change the namespace and expect it to work. You need to figure out how to inject the configuration into your class. It would be a lot easier if you just extend the Pimple class instead of building a wrapper around it. 

Besides that, the config.php file was build for pimple 1. There have been some changes in pimple 3.

**Comment by Sam-Burns** [comment]
@xtreamwayz The config gets injected [here](https://github.com/zendframework/zend-expressive-skeleton/blob/master/src/ExpressiveInstaller/Resources/config/container-pimple-interop.php#L12), doesn't it?  My container wrapper should be a drop-in replacement for the one you were using before, so I'm sure that injection will work ok.

**Comment by weierophinney** [comment]
Superceded by #49

**Pull request closed without merging**
