### PR TITLE
Aura.Di and Pimple container configuration moved to separate repositories

### LINKED ISSUE #168: Refactor the container config out of the skeleton
I think the code to build the pimple and aura.di containers should be refactored into their own repositories. Right now if there is a bug in that code we can't push fixes. The same goes for improvements, we can't push changes.

More than this should be into its own package:

```php
<?php

use Zend\ServiceManager\Config;
use Zend\ServiceManager\ServiceManager;

// Load configuration
$config = require __DIR__ . '/config.php';

// Build container
$container = new ServiceManager();
(new Config($config['dependencies']))->configureServiceManager($container);

// Inject config
$container->setService('config', $config);

return $container;
```

So basically the bare minimum should be inside the skeleton (like zend-servicemanager) and everything else taken out. Which means creating a zend-expressive-pimple and a zend-expressive-auradi package with a Config or ContainerBuilder class that translates zend-servicemanager configuration to those containers.

### PR DESCRIPTION
**Pull request by webimpress**
Resolves #168 

~~I've talked with @weierophinney and we'll move these repositories to `zendframework` org (not sure when, after zend-con...?)~~
**Update (21 Nov 2017):** ext repos moved into `zendframework` org and PR updated.

I don't see any advantages of using "extensions" with Pimple, as we have "delegators", and it works (almost) the same way. I saw, that it has been added by in https://github.com/zendframework/zend-expressive-skeleton/commit/23294c73699dd56af351939e6f09331834b96ee9 by @pine3ree, so maybe you could provide an example when we need 'extensions' and we can't use 'delegators', please? I can see that with extension we get `originService` in the factory, but with delegators we get callback, which returns `originService`, so basically it's the same... Pimple 'extensions' with expressive were not documented; only one places, where I found it is in release notes: https://github.com/zendframework/zend-expressive-skeleton/releases/tag/1.0.3. Unfortunately here was said wrong:
```php
return [
    'dependencies' => [
        'extensions' => [
            SomeClass::class => ExtendingFactory::class,
        ],
    ],
];
```
In code we expects **list** of extension factories, not just a one factory for the service (also list we expects for delegators). I feel that is duplicated functionality slightly changed, so we should remove one, and IMHO keep just delegators, as these works the same across `Zend\ServiceManager`, `Aura.Di`, `Pimple`.

/cc @xtreamwayz

### CODE REVIEW

**Comment by xtreamwayz** [comment]
Is there a reason why the packages still have a beta version (<1.0). Do they need more testing? 

I rather have a 1.0.0 release so if there are patches to those dependencies users will get those. If a 0.3.0 version would be released, they would not get it and need to upgrade manually.

**Comment by webimpress** [comment]
@xtreamwayz I would remove 'extensions' in pimple implementation. Please see above my PR description for more details. Then we can tag them as 1.0.0 I think.

**Comment by weierophinney** [comment]
> Is there a reason why the packages still have a beta version (<1.0). Do they need more testing?

They've not been tested _in production_ yet. That's the main concern I have with tagging them as stable 1.0. That said, they're based on stuff that we know already works, so I'm fine with tagging 1.0 versions.

**Comment by webimpress** [comment]
@weierophinney @xtreamwayz what if we tag 1.0.0 only with PHP 7.1 support? So when we move all expressive modules to support PSR-15 and PHP 7.1+ then we release these also with PHP 7.1+ as 1.0.0?

**Comment by weierophinney** [comment]
> what if we tag 1.0.0 only with PHP 7.1 support? So when we move all expressive modules to support PSR-15 and PHP 7.1+ then we release these also with PHP 7.1+ as 1.0.0?

I'd be okay with that; I'd rather not have an interim release between v2 and v3 for Expressive and the skeleton, other than the alpha or betas we do to help folks test the transition to PSR-15.

**Pull request merged**
