### PR TITLE
Lightweight module system - configuration manager v2

### PR DESCRIPTION
**Pull request by mtymek**
This PR replaces #26.

Another approach for adding modularity for Expressive apps. New syntax for building app config become simpler:

```php
$configManager = new ConfigManager(
    [
        new PhpFileProvider('config/autoload/{{,*.}global,{,*.}local}.php'),
        AppConfig::class,
    ]
);

return new ArrayObject($configManager->getMergedConfig());
```

`ConfigManager`'s workflow:
* if config cache file (`data/cache/app_config.php`) exists, then it is read and returned with no other processing (fast);
* if it is not available, then list of "config providers" passed to constructor is iterated, and config is merged (flexible)

"Config provider" is now an invokable class that resembles ZF2 module:

```php
class AppConfig
{
    public function __invoke()
    {
        // return array...
        return include __DIR__ . '/../config/module.config.php';
    }
}
```

Providers can also return a generator (for example, `PhpFileProvider` is using this feature). This gives us simple syntax (you pass all providers in a single array), and efficiency - if config cache exists, we don't have to call `glob`. 

This allows having similar application structure as ZF2 skeleton:

image

See [README](https://github.com/mtymek/expressive-config-manager#expressive-configuration-manager) for more details.

### CODE REVIEW

**Comment by xtreamwayz** [comment]
Although I understand the need for a modular structure, shouldn't the choice be left to the user what he wants? Looking at the changes, a modular structure is forced in this pull request.

Different structures are discussed here: zendframework/zend-expressive#176

**Comment by mtymek** [comment]
Right, my intention was not to change existing structure. I did this to show you guys what is possible.

I refactored my PR - now the changes to skeleton are minimal. If somebody wants to use modules, he can add them by himself.

**Comment by mtymek** [comment]
Rebased with current master.

**Comment by vaclavvanik** [comment]
@mtymek +1

**Comment by ojhaujjwal** [comment]
Wow. I love this idea. +1 from me :+1:

**Comment by mtymek** [comment]
Updated to latest version of `ConfigManager`. GlobFileProvider was renamed to PhpFileProvider, to better reflect what kind of config files it loads.

BTW, this version also supports loading and merging other config formats (INI, XML, ...) using `zend-config`.

**Comment by xtreamwayz** [comment]
I'm still not convinced by this. Looking at the source code, all it does is loading the configuration from locations outside the standard config path. Adding these 3 lines of code to the config file will do the same:

```php
// Load configuration from all modules e.g. src/App/Config/*.global.php
foreach (Glob::glob('src/*/Config/{{,*.}global,{,*.}local}.php', Glob::GLOB_BRACE) as $file) {
    $config = ArrayUtils::merge($config, include $file);
}
```

Maybe what would be useful is mentioning projects like this somewhere in the zend-expressive docs, so they can be found easily.

**Comment by mtymek** [comment]
Well, if you want to support caching, you get a bit more logic than just 3 lines, and you're going to repeat them over and over again in all Expressive apps.

What's more important, main purpose of this project is something different than simply loading config files. You can have multiple components bringing their own configuration that you enable just by adding providers to the list:

```php
$configManager = new ConfigManager(
    [
        new PhpFileProvider('config/autoload/{{,*.}global,{,*.}local}.php'),
        AppConfig::class,
        BlogConfig::class,
        GithubApiConfig::class,
        // ...
    ]
);
```

This brings experience similar to ZF2 module system, without its disadvantages. You can distribute your package together with config provider and consumers can plug it in just by adding single line of code, saving time required to wire things together. No one is forced to use it, but it really helps if you are building anything more complex.

**Comment by codeliner** [comment]
And not to forget: with the `ConfigManager` you can easily control the order of module configs which enables you to override third-party module configuration.

**Comment by weierophinney** [comment]
@mtymek I think I'd like to add this to the skeleton by default for 1.1. My thought process on how to make that happen is:

- Fork your expressive-config-manager to the zendframework organization
- Rename the composer package to `zendframework/zend-expressive-config-manager`
- Make that package required by the skeleton
- Update the `config/config.php` file accordingly
- Make the `src/App` directory a "module" (have it provide configuration for itself)

This latter will actually simplify the "minimal"/"full" install a fair bit, as we won't have to provide different configuration; we either provide the `src/App` directory or we don't.

Regardless, the proposed changes would require a brand new PR, as the approach differs from what you did here. You willing to work on it following the stable release?

**Comment by mtymek** [comment]
Sure, I will take it.
One thing suggested by @codeliner: since it can be used for non-expressive projects as well, what about renaming it to 'zendframework/zend-configmanager'?

**Comment by bakura10** [comment]
Hi,

I've read a bit about this. For me there is one problem is that this is not "transitive". For instance, let's say your application is dependant of a module "A". You can explicitely add the module "A" to your config and it will work.

However the module "A" itself depends on module "B", which depends itself on module "C". As of today, you need to introsepct the dependencies of A, and make sure you do not forget any of the nested dependencies, which not only is complicated but is quite error-prone.

Also, the fact that we need to add a class once again tie any module/library to Expressive, which is what we'd like to avoid especially with PSR7 and interoperability.

@danizord suggested a different idea based on a Composer hook that seemed superior. Basically the idea is to add that in your config:

```json
"extra": {
        "expressive-config": [
            "config/dependencies.global.php",
            "config/middleware-pipeline.global.php",
            "config/routes.global.php"
        ]
    }
```

This makes it completley independant (well, except this small part in the config), and also can allow the transitive stuff as the hook will iterate all the installed modules.

The only drawback is that it is hard to specify order, but again I think this can be extended to something like that: 

```json
"extra": {
        "expressive": {
            "after": "another-module",
            "before": "another-module",
            "config": [
               "config/dependencies.global.php",
               "config/middleware-pipeline.global.php",
               "config/routes.global.php"
           ]
        }
    }
```

This would means that the config is merged "after" or "before" another module.

What are the drawbacks of such a solution?

**Comment by xtreamwayz** [comment]
@mtymek I would even go a step further and merge it with zend-config.

@bakura10 Something like that is possible but not out of the box. You need something that tells composer and the installer to read that config from composer.json. Right now we remove the installer after it is done. So you need something like this: https://github.com/composer/installers. So basically you need to add something to expressive or composer to make it aware about the modules that are being installed anyway and this will be a dependency forever. If you remove it, it won't work anymore.

So whatever you want to do, nothing will work out of the box. If you go for the composer/installers route, you end up copying a config file to a location that expressive knows about.

> This would means that the config is merged "after" or "before" another module.
> What are the drawbacks of such a solution?

Now that I'm thinking about it.... If you go the composer.json->extra->expressive route... Expressive needs to load the project composer.json. Than it needs to load the composer.json files from all vendor/modules mentioned in the extra section. After that all module-dependent-vendor/modules, etc. After that it needs to process what to load and in what order. And finally load them. Of course this needs to be cached.

So basically at the end, you still need to have something like a config manager to load all configuration for all modules and their dependencies.

---

Having said that, what you want to achieve with default configuration? You want to set defaults right? Telling expressive where to find the default config seems to be a pain since there is no standard yet. (*I can't believe I'm saying this @sandrokeil* but...) The solution might be / is [interop-config](https://github.com/sandrokeil/interop-config). It's being prepared for PSR. What you can do is set defaults inside the factories or throw errors if the config is not there and the user should add it. If you go that route for all modules you **do** have a **config standard** that might eventually become a PSR standard. This way we don't need to invent stuff and build composer installers to detect modules or tell expressive where to find config files since the config is either in the factories, or the factories know where to find the defaults. (Basically **keep the responsibility to the factories and not force a framework x or framework y structure**)

All default settings are set inside the factories and everything that a user needs to set or can override can be set in the projects config/autoload path.

interop-config has been tested a lot but it might not be perfect yet. This would be a great time to give those guys a hand where needed and make a standard for configuration which we can use in PSR-7 modules and everywhere else.

Just my 2 cents.

**Comment by bakura10** [comment]
> Now that I'm thinking about it.... If you go the composer.json->extra->expressive route... Expressive needs to load the project composer.json. Than it needs to load the composer.json files from all vendor/modules mentioned in the extra section. After that all module-dependent-vendor/modules, etc. After that it needs to process what to load and in what order. And finally load them. Of course this needs to be cached.

Not exactly. It's not the expressive app that contains the extra, but the dependant modules. So the logic is that when you "composer update", you retrieve all dependant module, check if they have an extra[expressive], and if so, you retrieve the config files indicated in this extra, and merge them into a config file that you end up copying into your app.

**Comment by xtreamwayz** [comment]
Right, so you end up with building a composer/installer type for expressive modules. I still think that it can be kept a lot simpler by going the interop-container route and try to get that accepted as a PSR standard. No need for a new composer/installer type or load extra config. It's all inside the factories or overridden / set by config/autoload/<module>.global.php.

**Comment by bakura10** [comment]
Definitely. But for now, I can't see to see how your approach can be superior. The composer installer I'm suggesting is actually quite simple (would fit in a few dozen line of code I suppose), and at least it does not require you to write a specific class (hence tying your module to a specific Expressive convention), and resolve the issue of library deing dependant of another library, with recursive config.

**Comment by RalfEggert** [comment]
@bakura10 
Just a quick question, maybe I didn't get the way it will work. 

Would the composer based config stuff mean that I need to do a composer update whenever I change a config in any of the modules? If yes, that will make it much harder for beginners to understand. 

Anyway, I think that the solution of @mtymek is much easier to understand.

**Comment by xtreamwayz** [comment]
@bakura10 Ok, so let's get a bit deeper into this. What is it that you are actually trying to do? 

1. Copying a config file upon installing a module and its dependencies?
This can and will be a pain. What if there is a new version of the module with new config settings. You can't copy the file again since a user might have changed some settings already.

2. Reading module config files and merge them into the existing application configuration?
This can be done and is actually quiet nice. You read the config files mentioned in composer.json and all it's dependencies. Read the project config files and merge them to specific files if they don't exist yet. In this case you keep adding newly introduced config settings.

> Would the composer based config stuff mean that I need to do a composer update whenever I change a config in any of the modules? If yes, that will make it much harder for beginners to understand.

I think we are talking about modules you require with composer right? Not modules in src/ModuleX or src/ModuleY.

**Comment by RalfEggert** [comment]
Well, the idea of the `ConfigManager` is to add config files outside of the /config/autoload path. Having a modular structure would mean to have config files wherever the module files are located. That was my understanding.

**Comment by danizord** [comment]
Actually I was thinking about a composer plugin (not a composer installer) that attaches to composer update/install event, fetches the registered config files from `extra->expressive-config` key and store **the path** of these files so that when doing `require 'vendor/expressive-config.php'` you get all these config files merged.

I'm working on implementation right now so that you guys can understand it better looking at the code. Ah, untill implementation is not done, you can see a short description here: https://github.com/danizord/expressive-config/blob/master/README.md

**Comment by danizord** [comment]
@RalfEggert 
>Would the composer based config stuff mean that I need to do a composer update whenever I change a config in any of the modules? If yes, that will make it much harder for beginners to understand.

**Comment by danizord** [comment]
@RalfEggert 

>Would the composer based config stuff mean that I need to do a composer update whenever I change a config in any of the modules? If yes, that will make it much harder for beginners to understand.

Nope. It stores only the path of these config files. Merging happens on runtime when you call `require 'vendor/expressive-config.php'`

**Comment by bakura10** [comment]
Exactly. That's the idea. And if a third-party module is updated and add one more config path, it will be added on next "composer update" (that you will need to do anyway to retrieve the latest version of the library).

I suppose that this merging would also be cached, but for me this approach is far superior (work with recursive modules), does not tie your module/library to Expressive, does not require additional wiring code, does not force the consumer to manually add each module one by one.

As said the only minor drawback is the impossibility to control the order easily, but I'd say that as soon as your application config is merged at the end of the aggregated config, it will work 99% of the time.

**Comment by RalfEggert** [comment]
@danizord 

Thanks for clarification. But I am still no sure which solution is better for daily handling.

Anyway, the solution of @mtymek doesn't tie your modules to Expressive as well.

**Comment by bakura10** [comment]
Well in a certain way yes as you need to create a specific class. But as said this is not the biggest problem. Biggest one being that this approach is not recursive. Which happen many times (in our project we are using a base client library that is used by a common library that is used by our Expressive app :).

Envoyé de mon iPhone

**Comment by weierophinney** [comment]
@bakura10 The problem you're outlining (recursive addition of dependencies) is separate from configuration. It's something that projects like zend-component-installer may be able to assist (I'm considering similar functionality for Expressive, once we have a reasonable idea of what re-usable middleware *packages* look like).

The claim that an approach like the proposed config manager ties things to Expressive is one I find interesting, as I don't share that point of view at all; what it *does* do is tie you to a specific *configuration* schema however, and even your own proposals do that. What's interesting is that this can be entirely opt-in; if you opt-in to the installer mechanism, you're indicating that your project *configuration* follows a specific schema. Similarly, with the proposed configuration manager, you're doing the same; the difference is *how you provide the configuration*.

With your proposed solution, you're providing configuration *files*, which then need to be moved into the *application configuration*. This works, but poses a rather large problem: if an update to a "module" (for lack of a better word) provides updated configuration, and you have *local* changes to the configuration that was originally copied in, it will be overwritten. *You*, Michaël, may feel that's an edge case, but I know from experience that it *will* happen, and developers will consider that a bug. Which then means we have to do comparisons between the original configuration and the installed configuration prior to updating, or we have to create a "`.old`" file so developers can compare between the updated and what they had before.

The solution proposed by @mtymek resolves that because the configuration is pulled from the package itself at runtime (caching is recommended!!!), which means any configuration in the `config/autoload/` path is for *overriding* such settings. This prevents the update situation described above. Additionally, because the configuration is in the packages themselves, this also means that you can have an arbitrary configuration scheme for your application; you opt-in to pulling the configuration from these packages. What that means, however, is:

- You have to manually update the list of packages with configuration.
- You have a class per package that returns configuration.

Regarding that first point, this exact situation is what we have in ZF2 currently for modules, and which the zend-component-installer solves; as such, a similar approach can be used for any application that is going to tie into this. (Optionally, you could likely use Puli to accomplish this!) 

Regarding the class-per-package, that can be either a pro or a con depending on your point of view. Some folks don't like the idea of an additional class for describing configuration. On the flip side, others don't like configuration files, and would prefer a configuration class. (E.g., AuraPHP tends towards configuration *classes*, even for DI!) Considering it can be an invokable, and would not require even implementing an interface, this doesn't feel like an onerous requirement.

Which gets us back to the recursive dependencies bit. With an installer script such as zend-component-installer, what's interesting is that because Composer does a depth-first installation, if you assume that a package that extends another package needs to have the configuration appear after the original, you as long as the installer *appends* new packages to a list of installed packages providing configuration, they'll be in the correct order! As such, this combination — configuration manager + installer script — seems like a solid, turnkey approach to the issue.

**Comment by mtymek** [comment]
@bakura10 on top of what @weierophinney wrote, you can start with my solution directly, and then add composer-based config provider:

```php
$configManager = new ConfigManager(
    [
	// default configuration
	new ComposerConfigProvider(/* ... */),
	
	// override
        new PhpFileProvider('config/autoload/{{,*.}global,{,*.}local}.php'),        
    ]
);
```

@danizord's solution can be mixed together as well:

```php
$configManager = new ConfigManager(
    [
	// default configuration
        new PhpFileProvider('vendor/expressive-config.php'),
        
        // override
        new PhpFileProvider('config/autoload/{{,*.}global,{,*.}local}.php'),
    ]
);
```

As you see, we can have something simple but limiting you in any way. You can do whatever you need inside your own components and they will still play nicely with others.

**Comment by mtymek** [comment]
@xtreamwayz I don't like the idea of merging it into `zend-config`, as it serves slightly different purpose. I prefer to have a few smaller, dedicated components than one monolithic library. Almost every application needs some kind of configuration management but not many need to save configuration.

@weierophinney what's your view on naming it `zendframework/zend-configmanager`?

**Comment by sandrokeil** [comment]
The order of the modules should be configured by the user and I like the solution of the `ConfigManager`.  As @xtreamwayz mentioned, a config standard is not easy. The first `interop-config` approach with `vendor.package[.id]` was not the best solution, so [I'm working to make it flexible](https://github.com/sandrokeil/interop-config/pull/26). Config files are good, but I really like to see in a factory which configuration is needed. This is a huge advantage for the user and you could also generate your configuration files from these factories.

Let's take a look at the [`TwigRendererFactory` example with `interop-config`](https://github.com/sandrokeil/interop-config/blob/flexible-dimensions/doc/book/examples.md#use-arbitrary-configuration-structure). It's so easy to determine the needed configuration.

```php
namespace Zend\Expressive\Twig;

use Interop\Container\ContainerInterface;
use Twig_Environment as TwigEnvironment;
use Twig_Extension_Debug as TwigExtensionDebug;
use Twig_ExtensionInterface;
use Twig_Loader_Filesystem as TwigLoader;
use Zend\Expressive\Router\RouterInterface;

// interop-config
use Interop\Config\ConfigurationTrait;
use Interop\Config\RequiresConfig;
use Interop\Config\ProvidesDefaultOptions;

class TwigRendererFactory implements RequiresConfig, ProvidesDefaultOptions
{
    use ConfigurationTrait;

    /**
     * Uses root config to retrieve several options
     *
     * @return array
     */
    public function dimensions()
    {
        return [];
    }

    /**
     * This is the whole config structure with default settings for this factory
     */
    public function defaultOptions()
    {
        return [
            'debug' => false,
            'templates' => [
                'extension' => 'html.twig',
                'paths' => [],
            ],
            'twig' => [
                'cache_dir' => false,
                'assets_url' => '',
                'assets_version' => '',
                'extensions' => [],
            ],
        ];
    }

    // __invoke() and injectExtensions() method
 
    // The mergeConfig function is not needed anymore
    // private function mergeConfig($config)
}
```

**Comment by weierophinney** [comment]
@mtymek With regards to where the code should live, I'm torn. It's in the same domain as zend-config (configuration!), but, unlike zend-config, it's not about configuration _files_, but rather _aggregating_ configuration that is already in native PHP. As such, I tend to concur: separate component. I'd argue for `zend-config-aggregator`, however.

**Comment by mtymek** [comment]
@weierophinney `ConfigAggregator` looks good - better describes what this library does than "config manager". Feel free to fork my repo any time. I will rename the classes and add stuff like license information.

**Comment by bakura10** [comment]
Hi,

I've played a bit with that and actually I was wrong and I kinda like the approach after all. I thought that the dependencies to Expressive-Config-Manager should be added to ANY modules, but actually it's only for the consuming application.

The AppConfig class added in a module just returns a config so theorically it could be used for any frameworks.

Therefore, +1 for including this as part of default Expressive :).

**Comment by mtymek** [comment]
Happy to see that you like it @bakura10! :smile:

**Comment by Ocramius** [comment]
Just adding my current approach to the pile.

I ended up having something like following in my `index.php`

```php
<?php

(new \VendorName\ZendExpressive\ApplicationRunner(
    __DIR__ . '/..',  //working dir
    __DIR__ . '/../data/config-cache.php',
    new BaseExpressiveModule(),
    new Module1(),
    new Module2(),
    new Module3(),
    new Module4(),
    new Module5(),
    new GlobConfigModule(__DIR__ . '/../config/autoload/{{,*.}global,{,*.}local}.php'),
));
```

Where each module simply implements `ModuleConfiguration`:

```php
interface ModuleConfiguration
{
    public function __invoke() : array;
}
```
```php
class Module1 implements ModuleConfiguration
{
    public funciton __invoke() : array
    {
        return [
            'routes' => [
                [
                    'name' => 'my-awesome-shite',
                    'path' => '/awesome',
                    'middleware' => Module1\AwesomeAction::class,
                    'allowed_methods' => [Methods::GET],
               ],
        ];
    }
}
```

This got rid of:

 * merged config confusion - it's now up to me
 * module autoloading - it's just up to composer
 * module instantiation - I can pass arguments to my modules
 * module loading order
 * module validation - it's just an interface and a variadic argument

Hope that helps.

Also, I will ask my client if this can be open-sourced, since I feel like the design is quite simple and clean.

**Pull request closed without merging**
