### PR TITLE
Symfony DI container support

### PR DESCRIPTION
**Pull request by jsoumelidis**
Following the latest approach for alternative containers as suggested at [#170](https://github.com/zendframework/zend-expressive-skeleton/pull/170)

### CODE REVIEW

**Comment by xtreamwayz** [comment]
Thanx @jsoumelidis. I had a quick look at the code and it looks good to me. Staged for a 3.0 release.

**Comment by xtreamwayz** [comment]
Merged into release-3.0.0. Thanx @jsoumelidis!

**Comment by jsoumelidis** [comment]
:)
I noticed that a file used by the old approach is still there.
I'll create a new PR that removes file 'src/ExpressiveInstaller/Resources/config/sf-container.global.php'

**Comment by xtreamwayz** [comment]
I just found that file while refactoring a bit. I couldn't figure out why it was there.

**Pull request closed without merging**
